config/routes.rb
Csc517proj1::Application.routes.draw do
  resources :votes

  resources :posts do
    collection do
      get "all"
      post "new_reply"
      post "search"
      get "top"
    end
  end

  resources :users do

     get :details, :on => :member

  end

  get "login", :to => "users#login"
  post "login", :to => "users#login"
  get "logout", :to => "users#logout"
  get "reports", :to => "users#reports"

  root :to => "posts#top"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :votes

  # Attributed used to store the password passed in by the forms. This is necessary
  # to be able to encrypt the password before storing it into the database.
  attr_accessor :rpassword

  # Attribute used when creating or editing a user. The currently logged in user's id
  # is stored here for use with validation.
  attr_accessor :current_userid

  # Validations
  # The username is required, must be alphanumeric characters, and must be unique in the database.
  validates :username, :format => { :with => /\A[a-zA-Z0-9]+\z/, :message => "The username must be present and only contain alphanumeric characters." }
  validates :username, :uniqueness => true

  # The user must provide their name.
  validates :name, :presence => true

  # The is_admin field must be a boolean.
  validates :is_admin, :inclusion => { :in => [true, false] }

  # Password field is required and must be at least 6 characters long if it is a new
  # user or if the editing user provided a password.
  validate :password_requirements
  def password_requirements
    if id.nil? or ! rpassword.empty?
      errors.add(:base, "You must provide a password at least 6 characters long.") if rpassword.length < 6
    end
  end

  # Only administrators should be able to create administrator accounts.
  validate :only_admins_can_create_admins
  def only_admins_can_create_admins
    if is_admin and (current_userid.nil? or ! User.find(current_userid).is_admin)
      errors.add(:base, "Only administrators can create administrators.")
    end
  end

  # Callback necessary to encrypt the password before saving it.
  before_save do |u|
    if ! u.rpassword.empty?
      u.password = User.encrypt_pw(u.rpassword)
    end
  end

  # Function to check the username and password provided by the login form and return
  # the result of the query.
  def self.authenticate(u, p)
    User.find(:first, :conditions => ["username = ? AND password = ?", u, User.encrypt_pw(p)])
  end

  def self.encrypt_pw(p)
    Digest::SHA1.hexdigest(SALT_KEY + p)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Make sure the user is logged in to access these actions.
  before_filter :login_required, :except => [:login,:new,:create,:show]
  before_filter :yours_required || :admin_required, :only => [:edit, :update]
  before_filter :admin_required, :except => [:login,:logout,:new,:create,:show,:edit,:update]

  def login
    # Make sure the authentication parameters were provided.
    if params.has_key?(:username) and params.has_key?(:rpassword)
      # Authenticate using the posted credentials.
      user = User.authenticate params[:username], params[:rpassword]
      # Credentials were valid if the user var is not nil.
      if user != nil
        # Save the ID of the authenticated user.
        session[:id] = user.id
        # Now that the user is logged in, decide where to send them.
        session.has_key?(:return_to) ? redirect_to(session[:return_to]) : redirect_to("/")
      else
        flash[:error] = "The credentials you provided were invalid."
        redirect_to "/login"
      end
    end
  end

  def logout
    reset_session
    redirect_to "/"
  end

  def reports
    @users = User.all
    render 'users/user_report'
  end

  def details
    @user = User.find(params[:id])
    render 'users/ind_report'
  end

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    @user.current_userid = @current_user.id if ! @current_user.nil?
    if @user.save
      if ! @current_user.nil?
        redirect_to @user, :notice => 'User was successfully created.'
      else
        redirect_to '/login', :notice => 'Your account was successfully created. You can now login.'
      end
    else
      render :action => "new"
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])
    @user.current_userid = @current_user.id if ! @current_user.nil?

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])

    @posts = Post.all
    @posts.each do |post|
      if(post.user_id == @user.id)
        post.destroy
      end
    end

    @votes = Vote.all
    @votes.each do |vote|
      if(vote.user_id == @user.id)
        vote.destroy
      end
    end

    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :rpassword, "Password" %><br />
    <%= password_field :user, :rpassword %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
<% if @current_user and @current_user.is_admin %>
  <div class="field">
    <%= f.label :is_admin %><br />
    <%= f.check_box :is_admin %>
  </div>
<% else %>
  <div class="field">
    <%= f.hidden_field :is_admin, :value => false %>
  </div>
<% end %>
  <div class="actions">
    <button id="user_submit" name="commit" type="submit"><%= @current_user ? "Submit" : "Sign Up!" %></button>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Editing user</h2>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'User List', users_path %>

app/views/users/ind_report.erb
<h2>User Details</h2>
<p>
  <b>Username:</b>
  <%= @user.username %> </br>

  <b>Name:</b>
  <%= @user.name %>   </br>

  <b>Email:</b>
  <a href=mailto:<%= @user.email %>><%= @user.email %></a> </br>

  <b>Is admin:</b>
  <%= @user.is_admin %>  </br>
</p>

<h3>History</h3>

<u><b>Posts</b></u></br>

<% @posts = Post.where(:user_id => @user)%>

<table>
  <tr>
    <th align=left>Question</th>
    <th></th>
    <th align=left>Date Created</th>
  </tr>

<% @posts.each do |post| %>
  <tr valign="top">
    <td><%= post.data %></td>
    <td><font color="white"> abc </font>  </td>
    <td><%= post.created_at.localtime.to_date.to_formatted_s(:long) %></td>
  </tr>
<% end %>
</table>

<br />

<u><b>Votes</b></u></br>

<% @votes = Vote.where(:user_id => @user)%>

<table>
  <tr>
    <th align=left>Question</th>
    <th></th>
    <th align=left>Date Voted</th>
  </tr>

<% @votes.each do |vote| %>
  <% post = Post.find(vote.post_id) %>
  <tr valign="top">
    <td><%= post.data %></td>
    <td><font color="white"> abc </font>  </td>
    <td><%= vote.created_at.localtime.to_date.to_formatted_s(:long) %></td>
  </tr>
<% end %>
</table>

<br />



<%= link_to 'User Summary', "/reports" %>

app/views/users/index.html.erb
<h2>User List</h2>

<table class="list-display">
  <tr>
    <th width=100 align=left>Username</th>
    <!--<th width=100 align=left>Password</th>-->
    <th width=200 align=left>Name</th>
    <th width=200 align=left>Email</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.sort! {|u1, u2| u1.name <=> u2.name} %>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <!--<td><%= user.password %></td>-->
    <td><%= user.name %></td>
    <td><a href=mailto:<%= user.email %>><%= user.email %></a></td>
    <td><%= user.is_admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <% if user.id != @current_user.id %>
        <td><%= link_to 'Destroy', user, :confirm => 'Are you sure? All associated posts and votes will be deleted.', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<% if flash[:error] %>
<p class="error"><%= flash[:error] %></p>
<% end %>

<%= form_tag "/login" do %>
<table>
  <tr>
    <th><%= label_tag :username, "Username:" %></th>
    <td><%= text_field_tag :username %></td>
  </tr>
  <tr>
    <th><%= label_tag :rpassword, "Password:" %></th>
    <td><%= password_field_tag :rpassword %></td>
  </tr>
  <tr>
    <td align="center" colspan="2"><%= submit_tag "Login" %></td>
  </tr>
</table>
<% end %>

<script type="text/javascript">
  document.getElementById("username").focus();
</script>

app/views/users/new.html.erb
<h2><%= @current_user ? "New User" : "Sign Up Form" %></h2>

<%= render 'form' %>

<%= @current_user ? link_to('Back', users_path) : link_to('Back', '/') %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<!--<p>
  <b>Password:</b>
  <%= @user.password %>
</p>-->

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <a href=mailto:<%= @user.email %>><%= @user.email %></a>
</p>

<p>
  <b>Is admin:</b>
  <%= @user.is_admin %>
</p>

<% if !@current_user %>
  <form method="get" action="/login"><button>Login</button></form>
<%elsif @current_user and @current_user.is_admin %>
   <%= link_to 'Edit', edit_user_path(@user) %> |
   <% if @user.id != @current_user.id %>
        <%= link_to 'Destroy', @user, :confirm => 'Are you sure? All associated posts and votes will be deleted.', :method => :delete %> |
   <% end %>
   <%= link_to 'User List', users_path %>

<% end %>

app/views/users/user_report.erb
<h2>User Report</h2>

<table>
  <tr>
    <th width=120 align=left>Username</th>
    <th width=200 align=left>Name</th>
    <th width=100 align=left>Posts</th>
    <th width=100 align=left>Replies</th>
    <th width=100 align=left>Votes</th>
  </tr>

<% @users.sort! {|u1, u2| u1.name <=> u2.name} %>

<% @users.each do |user| %>


   <% num_replies=0 %>


   <% num_votes = Vote.where(:user_id => user).count %>
   <% num_posts = Post.where(:user_id => user).count %>


  <tr>
    <td><%= user.username %></td>
    <td><%= user.name %></td>
    <td><%= num_posts %></td>
    <td><%= num_replies %></td>
    <td><%= num_votes %></td>
    <td><%= link_to 'Details', details_user_path(user) %></td>

  </tr>
<% end %>
</table>

<br />