config/routes.rb
Csc517proj1::Application.routes.draw do
  resources :votes

  resources :posts do
    collection do
      get "all"
      post "new_reply"
      post "search"
      get "top"
    end
  end

  resources :users do

     get :details, :on => :member

  end

  get "login", :to => "users#login"
  post "login", :to => "users#login"
  get "logout", :to => "users#logout"
  get "reports", :to => "users#reports"

  root :to => "posts#top"

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  # Validation
  # Both the user and post are required to make a vote.
  validates :user_id, :presence => true
  validates :post_id, :presence => true

  # A user cannot vote on the same post more than once.
  validates :user_id, :uniqueness => { :scope => :post_id }

  # The person casting the vote cannot be the author of the post.
  validate :voter_cant_be_author
  def voter_cant_be_author
    tpost = Post.find(post_id)
    if tpost.user_id == user_id
      errmsg = "You can't vote on your own "
      errmsg += tpost.post_id ? "reply." : "post."
      errors.add(:base, errmsg)
    end
  end

  def self.has_voted?(userid)
    return where('user_id = ?', userid).count[0] > 0 ? true : false
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # Make sure the user is logged in to access these actions.
  before_filter :login_required
  before_filter :admin_required, :except => [:new,:create]

  # GET /votes
  # GET /votes.xml
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.xml
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.xml
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.xml
  def create
    @vote = Vote.new(params[:vote])
    @vote.save
    redirect_to request.referrer
    return

    respond_to do |format|
      if @vote.save
        format.html { redirect_to(@vote, :notice => 'Vote was successfully created.') }
        format.xml  { render :xml => @vote, :status => :created, :location => @vote }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.xml
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to(@vote, :notice => 'Vote was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vote.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.xml
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to(votes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>User</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.user %></td>
    <td><%= vote.post %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h2>New vote</h2>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @vote.user %>
</p>

<p>
  <b>Post:</b>
  <%= @vote.post %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>